# What hands.voice.speakers calls of sherpa-onnx, which ships no types.
from collections.abc import Sequence

import numpy as np

class SpeakerEmbeddingExtractorConfig:
    def __init__(self, *, model: str, num_threads: int = ...) -> None: ...

class OnlineStream:
    def accept_waveform(self, sample_rate: int, waveform: np.ndarray) -> None: ...
    def input_finished(self) -> None: ...

class SpeakerEmbeddingExtractor:
    dim: int
    def __init__(self, config: SpeakerEmbeddingExtractorConfig) -> None: ...
    def create_stream(self) -> OnlineStream: ...
    def compute(self, stream: OnlineStream) -> Sequence[float]: ...
